-- Users Table (Extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text unique not null,
  alias text,
  real_name text,
  membership_tier text default 'free' check (membership_tier in ('free', 'premium', 'business')),
  ad_preferences_allow_ads boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Policies for Profiles
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

-- Ads Table (For Business Users)
create table public.ads (
  id bigint generated by default as identity primary key,
  creator_id uuid references public.profiles(id) not null,
  title text not null,
  content text not null,
  target_audience text default 'all',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.ads enable row level security;

-- Policies for Ads
create policy "Ads are viewable by everyone"
  on ads for select
  using ( true );

create policy "Business users can create ads"
  on ads for insert
  with check ( auth.uid() = creator_id AND (select membership_tier from profiles where id = auth.uid()) = 'business' );

-- User Actions (Tracking Daily Limits)
create table public.user_actions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  action_type text not null, -- e.g., 'ripen'
  action_date date default current_date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.user_actions enable row level security;

-- Policies for Actions
create policy "Users can view own actions"
  on user_actions for select
  using ( auth.uid() = user_id );

create policy "Users can insert own actions"
  on user_actions for insert
  with check ( auth.uid() = user_id );

-- Database Function to Handle "Ripen" Logic safely
create or replace function attempt_ripen()
returns json
language plpgsql
security definer
as $$
declare
  user_tier text;
  daily_count int;
  user_id uuid;
begin
  user_id := auth.uid();

  -- Get User Tier
  select membership_tier into user_tier from profiles where id = user_id;

  -- Get Daily Count
  select count(*) into daily_count
  from user_actions
  where user_id = auth.uid()
  and action_type = 'ripen'
  and action_date = current_date;

  -- Check Logic
  if user_tier = 'free' and daily_count >= 25 then
    return json_build_object('success', false, 'reason', 'limit_reached');
  end if;

  -- Record Action
  insert into user_actions (user_id, action_type) values (user_id, 'ripen');

  return json_build_object('success', true);
end;
$$;
